export const currency = {
  "United Arab Emirates": "AED",
  "Afghanistan": "AFN",
  "Albania": "ALL",
  "Armenia": "AMD",
  "Netherlands Antilles": "ANG",
  "Angola": "AOA",
  "Argentina": "ARS",
  "Australia": "AUD",
  "Aruba": "AWG",
  "Azerbaijan": "AZN",
  "Bosnia and Herzegovina": "BAM",
  "Barbados": "BBD",
  "Bangladesh": "BDT",
  "Bulgaria": "BGN",
  "Bahrain": "BHD",
  "Burundi": "BIF",
  "United States": "USD",
  "Canada": "CAD",
  "Switzerland": "CHF",
  "Chile": "CLP",
  "China": "CNY",
  "Colombia": "COP",
  "Costa Rica": "CRC",
  "Cuba": "CUP",
  "Czech Republic": "CZK",
  "Denmark": "DKK",
  "Dominican Republic": "DOP",
  "Egypt": "EGP",
  "European Union": "EUR",
  "United Kingdom": "GBP",
  "Ghana": "GHS",
  "Hong Kong": "HKD",
  "Hungary": "HUF",
  "Iceland": "ISK",
  "India": "INR",
  "Indonesia": "IDR",
  "Iran": "IRR",
  "Iraq": "IQD",
  "Israel": "ILS",
  "Japan": "JPY",
  "Jordan": "JOD",
  "Kenya": "KES",
  "Kuwait": "KWD",
  "Malaysia": "MYR",
  "Mexico": "MXN",
  "Nepal": "NPR",
  "New Zealand": "NZD",
  "Nigeria": "NGN",
  "Norway": "NOK",
  "Oman": "OMR",
  "Pakistan": "PKR",
  "Philippines": "PHP",
  "Poland": "PLN",
  "Qatar": "QAR",
  "Romania": "RON",
  "Russia": "RUB",
  "Saudi Arabia": "SAR",
  "Singapore": "SGD",
  "South Africa": "ZAR",
  "Sri Lanka": "LKR",
  "Sweden": "SEK",
  "Switzerland": "CHF",
  "Thailand": "THB",
  "Turkey": "TRY",
  "United Arab Emirates": "AED",
  "Vietnam": "VND"
};
